version: '3'
services:
  gulp:
    build: .
    command: bash -c "gulp && gulp watch"
    volumes:
      - .:/app
      - /app/node_modules
  apache:
    image: php:7.0-apache
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    environment:
      - FORECAST_IO_API_KEY=280b615c4a69fe34235855040fd4dccc
